// Unified type barrel — re-exports all types from live.ts and connect.ts
// live.ts types take priority where names conflict (streaming context wins)

// ── Live / Streaming types ─────────────────────────────────────────────
export type {
  Series,
  Sermon,
  User,
  AuthSession,
  WatchlistItem,
  WatchHistoryItem,
  StreamLink,
  StreamSettings,
  Service,
  ServiceSchedule,
  PrayerRequest,
  Note,
  Theme,
  TabType,
  ChurchInfo,
  ServiceTime,
  Event,
  EventCategory,
  FAQ,
  FAQCategory,
  ChatSession,
  ChatMessage,
  ChatRateLimit,
  ChatRequest,
  ChatResponse,
  ChatSource,
  KnowledgeBase,
  SermonSummary,
  AdminStats,
  AdminTabId,
  AdminTab,
} from './live';

// ── Connect / Management types ─────────────────────────────────────────
export type {
  UserRole,
  AccountStatus,
  Gender,
  RuachBranch,
  CrosspointZone,
  UserAccount,
  Guest,
  ConnectCohortStatus,
  ConnectClassType,
  ConnectStudentStatus,
  ConnectCohort,
  ConnectClassSession,
  ConnectResource,
  ConnectStudent,
  ConnectAttendanceRecord,
  ConnectWarning,
  ExamStatus,
  QuestionType,
  ConnectExam,
  ExamQuestion,
  ConnectExamResult,
  LegacyMemberStatus,
  LegacyMemberRequest,
  DiscipleshipLevel,
  DiscipleshipCohortStatus,
  DiscipleshipStudentStatus,
  DiscipleshipCourse,
  DiscipleshipCohort,
  DiscipleshipClassSession,
  DiscipleshipResource,
  DiscipleshipStudent,
  DiscipleshipAttendanceRecord,
  DiscipleshipWarning,
  DiscipleshipExam,
  DiscipleshipExamResult,
  DiscipleshipProgress,
  Crosspoint,
  CrosspointMembership,
  CrosspointModule,
  DepartmentId,
  Department,
  SubTeam,
  DepartmentMembership,
  Suggestion,
  Notice,
  TransferRequest,
  DepartmentJoinRequest,
  FoodBankRequest,
  AttendanceImport,
  Member,
} from './connect';

// isMember is a value (function), not a type — re-export it directly
export { isMember } from './connect';
